services:
  app:
    image: ink-md-editor:latest
    container_name: ink-md-editor

    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3001

    ports:
      - "3001:3001"

    volumes:
      - ./notes:/app/notes

    restart: unless-stopped
